[experimental]

[server]
browser = "default"
follow_symlink = true

[language_servers.pylsp]
enable_flake8 = false
enabled = true
enable_ruff = true
enable_pyflakes = false
enable_pydocstyle = false
enable_mypy = true
enable_pylint = false

[save]
format_on_save = false
autosave_delay = 1000
autosave = "off"

[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[ai]
rules = ""
inline_tooltip = false
mode = "manual"

[ai.models]
custom_models = []
displayed_models = []

[ai.bedrock]

[ai.google]

[ai.anthropic]

[ai.open_ai]

[runtime]
default_sql_output = "auto"
default_auto_download = []
auto_reload = "autorun"
output_max_bytes = 8000000
on_cell_change = "autorun"
reactive_tests = true
std_stream_max_bytes = 1000000
auto_instantiate = true
watcher_on_save = "lazy"

[formatting]
line_length = 79

[package_management]
manager = "uv"

[mcp]
presets = []

[mcp.mcpServers]

[display]
code_editor_font_size = 14
reference_highlighting = false
default_width = "medium"
default_table_page_size = 10
theme = "system"
default_table_max_columns = 50
cell_output = "above"
dataframes = "rich"

[completion]
copilot = false
activate_on_typing = true

[diagnostics]
sql_linter = true

[snippets]
include_default_snippets = true
custom_paths = []
